apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
  namespace: default
spec:
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
        - name: streaming
          image: perceptionengine.azurecr.io/spatial-analysis-streamer:latest
          imagePullPolicy: IfNotPresent


