apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: streaming
  namespace: cluster-config-1
spec:
  targetNamespace: streaming
  releaseName: streaming
  chart:
    spec:
      chart: streaming
      sourceRef:      
        kind: Pod
        metadata:
          name: ubuntu
          labels:
            app: ubuntu
        spec:
          containers:
          - name: ubuntu
            image: ubuntu:latest
            command: ["/bin/sleep", "3650d"]
            imagePullPolicy: IfNotPresent
          restartPolicy: Always

