apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
  namespace: default
spec:
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: perceptionengine.azurecr.io/spatialanalysis-streaming-public:20240202.1
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: registry-credential


