apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: Deployment
metadata:
  name: streaming
  namespace: default
spec:
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
        - name: streaming
          image: docker.io/ubuntu:latest
          imagePullPolicy: IfNotPresent


