apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
  namespace: default
spec:
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: perceptionengine.azurecr.io/spatialanalysis-streaming-public:20240220.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /archon
        - name: dshm
          mountPath: /dev/shm
          mountPropagation: None
          readOnly: false
          subpath:
        env:
        - name: LAUNCHER_TYPE
          value: "kubernetes"
        - name: EULA
          value: "accept"
      imagePullSecrets:
      - name: registry-credential
      volumes:
      - name: config
        configMap:
          name: rtcv-config
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 536870912
