apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
  namespace: default
spec:
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: perceptionengine.azurecr.io/spatialanalysis-streaming-public:20240305.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "4"
          memory:
        volumeMounts:
        - name: config
          mountPath: /archon
        env:
        - name: LAUNCHER_TYPE
          value: "kubernetes"
        - name: EULA
          value: "accept"
        - name: VIDEO_RECORDING_BLOB_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: VIDEO_RECORDING_BLOB_CONTAINER_NAME
        - name: VIDEO_RECORDING_STORAGE_ACCOUNT_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: VIDEO_RECORDING_STORAGE_ACCOUNT_CONNECTION_STRING
        - name: VIDEO_URL_SAS
          valueFrom:
            secretKeyRef:
              name: azure-blob-secret
              key: VIDEO_URL_SAS
      imagePullSecrets:
      - name: registry-credential
      volumes:
      - name: config
        configMap:
          name: rtcv-config
