apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
  namespace: default
spec:
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: perceptionengine.azurecr.io/spatialanalysis-streaming-public:20240220.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "4"
          memory:
        volumeMounts:
        - name: config
          mountPath: /archon
        env:
        - name: LAUNCHER_TYPE
          value: "kubernetes"
        - name: EULA
          value: "accept"
        - name: VIDEO_RECORDING_BLOB_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: VIDEO_RECORDING_BLOB_CONTAINER_NAME
        - name: VIDEO_RECORDING_STORAGE_ACCOUNT_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: VIDEO_RECORDING_STORAGE_ACCOUNT_CONNECTION_STRING
      imagePullSecrets:
      - name: registry-credential
      volumes:
      - name: config
        configMap:
          name: rtcv-config
---
apiVersion: v1
kind: ConfigMap
metadata:
name: rtcv-config
labels:
  app: rtcv
data:
  archon-module-config.json: |-
    {
        "globalSettings": {
            "platformTelemetryEnabled": false,
            "customerTelemetryEnabled": false,
            "platformLogLevel": "verbose",
            "nodesLogLevel": "verbose"
        },
        "graphs": {
            "stream": {
                "operationId": "cognitiveservices.vision.cloudstream",
                "enabled": true,
                "instances": {
                    "instance1": {
                        "enabled": true,
                        "parameters": {
                            "VIDEO_URL": "rtsp://root:witwicsd@10.224.30.132/axis-media/media.amp?videocodec=h264",
                            "VIDEO_SOURCE_ID": "vp01-dev7",
                            "VIDEO_IS_LIVE": true,
                            "ENABLE_BLOB_HTTPS_CONNECTION": "false",
                            "EULA": "accept",
                            "CLOUD_OPERATION_CONFIG": "{\"operationId\":\"cognitiveservices.vision.spatialanalysis-recording.cloud\",\"version\":1,\"enabled\":true,\"platformLogLevel\":\"verbose\",\"nodesLogLevel\":\"verbose\",\"parameters\":{\"GRPC_PORT\":\"50051\",\"VIDEO_SOURCE_ID\":\"axisvideouploadinggraph\",\"MAXIMUM_VIDEO_DURATION_IN_SEC\":180,\"VIDEO_RECORDING_STORAGE_ACCOUNT_CONNECTION_STRING\":\"${VIDEO_RECORDING_STORAGE_ACCOUNT_CONNECTION_STRING}\",\"VIDEO_RECORDING_BLOB_CONTAINER_NAME\":\"${VIDEO_RECORDING_BLOB_CONTAINER_NAME}\"}}",
                            "CLOUD_ENDPOINT": "10.178.253.7:50051",
                            "CLOUD_API_KEY": "",
                            "USE_SSL": false,
                            "ENABLE_MOTION_DETECTION": false
                        }
                    }
                }
            }
        }
    }
